### ISSUE TITLE
Support for Kattis Subdomains

### ISSUE THREAD

**Issue by chenvictor** [ahmedsiad/Kattis-UI-Fix#6]
The current site access: `https://open.kattis.com/*` means the extension doesn't work on something like https://naipc19.kattis.com/problems/costofliving

Would be great if this could be changed (I assume it's not too complicated?)

**Comment by ahmedsiad** [comment]
Yeah all I had to do was change `https://open.kattis.com/` to `https://*.kattis.com/` to make it work with all possible subdomains. Thanks.
